// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAl40eTdZlpi5fIOiiYaDp6YX1sp9erkO4',
    appId: '1:718793385489:web:456a67928b59ed8d89f3b0',
    messagingSenderId: '718793385489',
    projectId: 'coalquip',
    authDomain: 'coalquip.firebaseapp.com',
    storageBucket: 'coalquip.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB26FTTHQBOzapURuy7S1k3g8Gbrnfg2ao',
    appId: '1:718793385489:android:9ca07e39035ab79e89f3b0',
    messagingSenderId: '718793385489',
    projectId: 'coalquip',
    storageBucket: 'coalquip.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWzhDkfs8Bj7639naUWapr7TP4Cy4lcy0',
    appId: '1:718793385489:ios:c772b22a2d06157b89f3b0',
    messagingSenderId: '718793385489',
    projectId: 'coalquip',
    storageBucket: 'coalquip.appspot.com',
    iosBundleId: 'com.example.dala',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWzhDkfs8Bj7639naUWapr7TP4Cy4lcy0',
    appId: '1:718793385489:ios:c772b22a2d06157b89f3b0',
    messagingSenderId: '718793385489',
    projectId: 'coalquip',
    storageBucket: 'coalquip.appspot.com',
    iosBundleId: 'com.example.dala',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAl40eTdZlpi5fIOiiYaDp6YX1sp9erkO4',
    appId: '1:718793385489:web:4a215d07f6a335a189f3b0',
    messagingSenderId: '718793385489',
    projectId: 'coalquip',
    authDomain: 'coalquip.firebaseapp.com',
    storageBucket: 'coalquip.appspot.com',
  );

}